name: Hola mundo Workflow este es el original

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Paso Hola mundo
        run: echo "Hola mundo desde GitHub Actions"
