name: Build
on:
  pull_request:
    branches:
      - main
 
  workflow_dispatch:    # Permite ejecución manual
    inputs:
      build_configuration:
        description: 'Build Configuration (Debug or Release)'
        required: false
        default: 'Release'
        type: choice
        options:
          - Debug
          - Release
      log_level:
        description: 'dotnet verbosity level'
        required: false
        default: 'normal'
        type: choice
        options:
          - quiet
          - minimal
          - normal
          - detailed
env: 
  DOTNET_VERSION: '10.0.x'
  BUILD_CONFIGURATION: 'Release'
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Mensaje Inicial
          run: echo "Iniciando workflow de CI"
        - name: Checkout del código
          uses: actions/checkout@v4
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{env.DOTNET_VERSION}}
        
        - name: Restore Dependencies
          run: dotnet restore src/Api/Api.csproj --verbosity ${{inputs.log_level || 'normal'}} 
          
        - name: Build del proyecto
          id: build-step
          # working-directory: 'src/Api'
          run: dotnet build src/Api/Api.csproj --configuration ${{env.BUILD_CONFIGURATION}}