name: Hola Mundo Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Paso Hola Mundo
        run: echo "Hola desde Github Actions"

      - name: Debug
        run: |
          echo "Debugging: GITHUB_REF: ${{github.ref}}"
          echo "Debugging: RUNNER_OS: ${{ runner.os}}"
